[steam-box]
image=archlinux:latest
pull=true
replace=true

# On reste vide ici pour la stabilité
additional_packages=

# On ne met RIEN dans additional_packages pour éviter le conflit de timing
# On fait TOUT dans le hook : Config Multilib -> Update -> Installation
init_hooks=printf "\n[multilib]\nInclude = /etc/pacman.d/mirrorlist\n" >> /etc/pacman.conf && pacman -Syy --noconfirm && pacman -S --noconfirm steam mesa lib32-mesa vulkan-radeon lib32-vulkan-radeon mesa-utils mangohud lib32-mangohud gamemode lib32-gamemode gamescope libcap && sudo pacman -Scc --noconfirm

exported_apps=steam

# executer distrobox assemble create --file /chemin/vers/steam-box.ini pour générer le container
