[work-box]
image=archlinux:latest
pull=true
replace=true

# On reste vide ici pour la stabilité
additional_packages=

init_hooks=sudo pacman-key --init && sudo pacman-key --populate archlinux && sudo pacman -Sy --noconfirm archlinux-keyring && sudo pacman -Su --noconfirm && sudo pacman -S --noconfirm git neovim tmux rsync wget curl fzf fd ripgrep python python-pip nodejs npm htop && sudo pacman -Scc --noconfirm

exported_apps=htop

# executer distrobox assemble create --file /chemin/vers/work-box.ini pour générer le container
